web:
  image: kaojo/wildfly
  links:
   - postgres
  ports:
   - "9990:9990"
   - "9999:9999"
   - "8080:8080"
  volumes_from:
   - jbossLog
postgres:
  image: kaojo/postgres
  environment:
  - POSTGRES_USER=kaojo
  - POSTGRES_PASSWORD
  volumes_from:
   - postgresVolumes
jbossLog:
  image: kaojo/jboss-log
  volumes:
    - /opt/de.kaojo/jbossLogs:/logs/jboss
postgresVolumes:
  image: kaojo/postgres-volumes
  volumes:
   - /opt/de.kaojo/postgres-config:/etc/postgresql
   - /opt/de.kaojo/postgres-log:/var/log/postgresql
   - /opt/de.kaojo/postgres-data:/var/lib/postgresql/data
